### PR TITLE
Limma voom for kmers

### PR DESCRIPTION
**Pull request by MarineAGLAVE**
It's me again ;)
I implemented a limma-voom for k-mers DE.
And now that I have tested and validated it on my data, I propose it to enrich the panel of statistical methods.

### CODE REVIEW

**Comment by jaudoux** [comment]
Everything looks great, thanks for this addition. I think many will benefit from this new test. Do you have comparison run times of the three methods (ttest, deseq2, limma-voom) of a large cohort ?

**Comment by MarineAGLAVE** [comment]
I didn't make the comparison on large cohorts (DESeq2 really took a lot of time).
On 17 samples (8 vs 9), 9046760 of k-mers in the masked-count.tsv, limma-voom is 10 times faster. This figure represente the run time only from the Rscript for DE k-mers (not jellyfish, merge countTable and genes analysis).
Comparison_methods

**Comment by jaudoux** [comment]
Awesome, that's a huge improvement !!!

**Comment by MarineAGLAVE** [comment]
Yes!! And very helpful on my project with large cohort ;)

**Pull request merged**
